### ISSUE TITLE
ericscript.pl not found insider Docker

### ISSUE THREAD

**Issue by Bontempogianpaolo1** [federicacitarrella/FusionFlow#35]
Error executing process > 'ericscript (reads)'

Caused by:
  Process `ericscript (reads)` terminated with an error exit status (127)

Command executed:

  #!/bin/bash
  
  export PATH="/path/to/miniconda3/envs/ericscript/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" 
  
  mkdir output && cd output
  
  ericscript.pl -o ./reads -db ../ericscript_db_homosapiens_ensembl84 ../reads_1.fq.gz ../reads_2.fq.gz

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 7: ericscript.pl: command not found

Work dir:
  /home/work/e7/96ae119c0bf3d042330e7f1320ad3c

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by Bontempogianpaolo1** [comment]
PATH is /opt/conda/envs/ericscript/bin

**Comment by Bontempogianpaolo1** [comment]
probability the ufficial pipeline  on the cloud is not updated

**Comment by federicacitarrella** [comment]
As you can see in the error message, it is looking for the ericscript.pl file in "/path/to/miniconda3/envs/ericscript/bin", maybe are you giving this path as input from the command line? In this case, you can delete it from the command line, so that it will take the default path from the configuration file

**Comment by federicacitarrella** [comment]
> export PATH="/path/to/miniconda3/envs/ericscript/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

As you can see in the error message, it is looking for the ericscript.pl file in "/path/to/miniconda3/envs/ericscript/bin", are you giving this path as input from the command line? In this case, you can delete it from the command line, so that it will take the default path from the configuration file

**Comment by Bontempogianpaolo1** [comment]
not at all! I used the command on the readme
